FROM phusion/baseimage
LABEL description="Installed PHP version:: php7.0-fpm; php7.0-mysql;"
MAINTAINER Mayank G <mg.devzone@gmail.com>

CMD ["/sbin/my_init"]

RUN apt-get update
RUN add-apt-repository ppa:ondrej/php-7.0